apiVersion: metering.openshift.io/v1alpha1
kind: ScheduledReport
metadata:
 name: demo-peak-cpu-usage-hourly
spec:
 generationQuery: "demo-peak-cpu-usage"
 gracePeriod: "5m"
 schedule:
   period: "hourly"
   hourly:
     minute: 0
     second: 0
