apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "jboss-cpu-core-seconds"
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: string
    unit: kubernetes_pod
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: node
    type: string
    unit: kubernetes_node
  - name: data_start
    type: timestamp
    unit: date
  - name: data_end
    type: timestamp
    unit: date
  - name: pod_usage_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: label
    type: string
  query: |
    SELECT
      timestamp '{| .Report.StartPeriod| prestoTimestamp |}' AS period_start,
      timestamp '{| .Report.EndPeriod | prestoTimestamp |}' AS period_end,
      pod,
      namespace,
      node,
      min(C."timestamp") as data_start,
      max(C."timestamp") as data_end,
      sum(pod_usage_cpu_core_seconds) as pod_usage_cpu_core_seconds,
      L.labels['label_com_redhat_product'] as label
    FROM {| generationQueryViewName "pod-cpu-usage-raw" |} as C
    JOIN {| dataSourceTableName "kube-pod-label-jboss" |} as L
        ON pod = L.labels['pod']
    WHERE C."timestamp" >= timestamp '{|.Report.StartPeriod | prestoTimestamp |}'
    AND C."timestamp" <= timestamp '{| .Report.EndPeriod | prestoTimestamp |}'
    GROUP BY namespace, pod, node, L.labels['label_com_redhat_product']
    ORDER BY namespace, pod, node ASC, pod_usage_cpu_core_seconds DESC
  reportQueries:
  - "pod-cpu-usage-raw"
  reportDataSources:
    - "kube-pod-label-jboss"
  view:
    disabled: true
