apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "demo-jboss-peak-cpu-usage"
spec:
  reportDataSources:
  - "kube-pod-label-demo"
  - "pod-usage-cpu-cores"
  view:
    disabled: true
  columns:
  - name: project
    type: string
  - name: pod
    type: string
  - name: label
    type: string
  - name: used_cores
    type: double
  query: |
    SELECT
        C.labels['namespace'] as project,
        C.labels['pod_name'] as pod,
        L.labels['label_com_redhat_product'] as label,
        max(C.amount) as used_cores
    FROM {| dataSourceTableName "pod-usage-cpu-cores" |} as C
    JOIN {| dataSourceTableName "kube-pod-label-demo" |} as L
        ON C.labels['pod_name'] = L.labels['pod']
    WHERE C."timestamp" >= timestamp '{|.Report.ReportingStart | prestoTimestamp |}'
        AND C."timestamp" <= timestamp '{| .Report.ReportingEnd | prestoTimestamp |}'
    GROUP BY C.labels['namespace'], C.labels['pod_name'], L.labels['label_com_redhat_product']
    ORDER BY project ASC, used_cores DESC
